=== api-evangelist/amazon-appflow/json-schema/appflow-register-connector-request-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-appflow/refs/heads/main/json-schema/appflow-register-connector-request-schema.json",
  "title": "RegisterConnectorRequest",
  "description": "RegisterConnectorRequest schema from Amazon AppFlow API",
  "type": "object",
  "properties": {
    "connectorLabel": {
      "type": "string",
      "maxLength": 256,
      "example": "MyCustomConnector",
      "description": "The name of the connector. The name is unique for each ConnectorRegistration in your Amazon Web Services account."
    },
    "description": {
      "type": "string",
      "maxLength": 2048,
      "example": "My custom connector for proprietary data source",
      "description": "A description about the connector that's being registered."
    },
    "connectorProvisioningType": {
      "type": "string",
      "enum": [
        "LAMBDA"
      ],
      "example": "LAMBDA",
      "description": "The provisioning type of the connector. Currently the only supported value is LAMBDA."
    },
    "connectorProvisioningConfig": {
      "type": "object",
      "properties": {
        "lambda": {
          "type": "object",
          "properties": {
            "lambdaArn": {
              "type": "string",
              "example": "arn:aws:lambda:us-east-1:123456789012:function:my-connector-function",
              "description": "Lambda ARN of the connector being registered."
            }
          },
          "description": "Contains information about the configuration of the lambda which is being registered as the connector."
        }
      },
      "description": "The provisioning type of the connector."
    },
    "clientToken": {
      "type": "string",
      "example": "client-token-500123",
      "description": "Idempotency token."
    }
  }
}

=== api-evangelist/amazon-appflow/examples/appflow-register-connector-request-example.json
{
  "connectorLabel": "MyCustomConnector",
  "description": "My custom connector for proprietary data source",
  "connectorProvisioningType": "LAMBDA",
  "connectorProvisioningConfig": {
    "lambda": {
      "lambdaArn": "arn:aws:lambda:us-east-1:123456789012:function:my-connector-function"
    }
  },
  "clientToken": "client-token-500123"
}
